mov = "data/movie/movies_metadata.csv"
rat = "data/movie/ratings.csv"
rat_small = "data/movie/ratings_small.csv"

genre_types = [
    "Action",
    "Adventure",
    "Animation",
    # "Children's",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Fantasy",
    # "Film-Noir",
    "Horror",
    "Musical",
    "Mystery",
    "Romance",
    # "Sci-Fi",
    "Thriller",
    "War",
    "Western",
    "Science Fiction",
    "Music",
    "Family",
    "Foreign",
    "History",
    "TV Movie",
    # "(no genres listed)",
]

all_cont_params = ["rating", "vote_average"]  # , "popularity"]
rating_column = ["rating"]
continuous_params = all_cont_params

my_params = {
    "Action",
    "Adventure",
    "Animation",
    # "Children's",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Fantasy",
    # "Film-Noir",
    "Horror",
    "Musical",
    "Mystery",
    "Romance",
    # "Sci-Fi",
    "Thriller",
    "War",
    "Western",
    "Science Fiction",
    "Music",
    "Family",
    "Foreign",
    "History",
    "TV Movie",
}

my_params_trash = {
    "Action": 0,
    "Adventure": 0,
    "Animation": 0,
    # "Children's":0,
    "Comedy": 0,
    "Crime": 0,
    "Documentary": 0,
    "Drama": 0,
    "Fantasy": 0,
    # "Film-Noir":0,
    "Horror": 0,
    "Musical": 0,
    "Mystery": 0,
    "Romance": 0,
    # "Sci-Fi",
    "Thriller": 0,
    "War": 0,
    "Western": 0,
    "Science Fiction": 0,
    "Music": 0,
    "Family": 0,
    "Foreign": 0,
    "History": 0,
    "TV Movie": 0,
    # "(no genres listed)",
}
